### ISSUE TITLE
groupoffice-container is empty

### ISSUE THREAD

**Issue by g-schmitz** [Intermesh/docker-groupoffice-development#2]
I followed the installation guide but when I came to the step of composer install there was the following error:

`Composer could not find a composer.json file in /var/www/html
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
`

I then bash'd into the container. What I saw was that the /usr/local/share/groupoffice as well as the /var/www directories are completely empty.

**Comment by tmikaeld** [comment]
Same here, would appreciate a fix. This issue in question was posted 15 days ago.

**Comment by mschering** [comment]
Sorry, I'll fix this on Monday.

**Comment by mschering** [comment]
I found the problem. It's because submodules are not automatically cloned. I've updated the readme with the correct command. Or you can do in your existing clone:

git submodule init 
git submodule update

**Comment by tmikaeld** [comment]
Thanks for fixing it! Will try it out
