### ISSUE TITLE
Writable config file issue & wrong port

### ISSUE THREAD

**Issue by tmikaeld** [Intermesh/docker-groupoffice-development#3]
On point five there's a link to port 8080, but the default install is linked to port 80.

The installer requires config.ini to be writable, but by default it isn't. 
Not sure which user should be used here, the existing file is set to root user.

MySQL doesn't seem to be initalized with a root password, the docker console gives:

```
error: database is uninitialized and password option is not specified 
  You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD

**Comment by mschering** [comment]
Thanks, I'll update that. Can you launch /install/install.php ?

This should pass the config.ini write check as it already has the correct values. I will think of a permanent solution.

**Comment by tmikaeld** [comment]
Thanks, I updated the issue with the MySQL problem.

**Comment by mschering** [comment]
I just pushed various fixes. Please stat over clean and everything should work as expected now!

**Comment by mschering** [comment]
Did this fix it for you? Can I close this one?

**Comment by tmikaeld** [comment]
Yes! Works perfectly, thanks 👍
